language: java
jdk:
  - oraclejdk8
sudo: false
notifications:
  email: false
script: "if [ ${TRAVIS_PULL_REQUEST} = 'true' ]; then mvn test -B; else mvn deploy -P duckswithsauce --settings .travis_settings.xml; fi"