language: java
jdk:
  - oraclejdk8
sudo: false
notifications:
  email: false
script: "if [ ${TRAVIS_PULL_REQUEST} = 'false' ] && [ ${TRAVIS_BRANCH} = 'master' ]; then mvn deploy -P duckswithsauce --settings .travis_settings.xml; else mvn test -B; fi"
branches:
  except:
    - /^[0-9]+\.[0-9]+\.[0-9]+$/
before_install:
  - pip install --user codecov
after_success:
  - codecov
