site_name: KICL Documentation
repo_url: https://github.com/KittehOrg/KittehIRCClientLib
pages:
- Home: index.md
- Events: events.md
- IRCv3 Support: ircv3.md
- Advanced:
  - Account Tracking: advanced/accounts.md
  - STS: advanced/sts.md
  - TLS: advanced/tls.md
  - TLS root import: advanced/tls_import.md
  - Twitch: advanced/twitch.md
  - WEBIRC: advanced/webirc.md
  - SASL: advanced/sasl.md
  - ECDSA: advanced/ecdsa.md
  - Alternative Authentication: advanced/alt_auth.md
markdown_extensions: [fenced_code]
theme: readthedocs
